# Generated by Django 5.0.2 on 2025-06-22 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profile_app', '0002_profile_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('done', 'done'), ('unRead', 'unRead'), ('read', 'read')], default='unRead', max_length=55)),
                ('link', models.CharField(blank=True, max_length=230, null=True)),
                ('title', models.CharField(blank=True, max_length=230, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_accepted', models.BooleanField(blank=True, default=False, null=True)),
                ('is_denied', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_receiver', to='profile_app.profile')),
                ('requestRelated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_requested', to='request_app.request')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_sender', to='profile_app.profile')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Post',
            },
        ),
    ]
