# Generated by Django 5.0.2 on 2025-07-05 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Request', 'verbose_name_plural': 'Request'},
        ),
        migrations.AlterField(
            model_name='request',
            name='requestRelated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_requested', to='request_app.request'),
        ),
    ]
