# Generated by Django 5.0.2 on 2025-06-21 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0002_profile_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('note', 'note'), ('image', 'image'), ('reels', 'reels')], default='note', max_length=30)),
                ('file_post', models.FileField(blank=True, null=True, upload_to='media/post/files/% Y/% m/% d/')),
                ('image_post', models.ImageField(blank=True, null=True, upload_to='media/post/images/% Y/% m/% d/')),
                ('caption', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fav_people', models.ManyToManyField(blank=True, related_name='fav_people_post', to='profile_app.profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_post', to='profile_app.profile')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_comment', models.ImageField(blank=True, null=True, upload_to='media/comment/images/% Y/% m/% d/')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fav_people', models.ManyToManyField(blank=True, related_name='fav_people_comment', to='profile_app.profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_comment', to='profile_app.profile')),
                ('replied_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repliedOn_comment', to='post_app.comment')),
                ('postRelated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='post_app.post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comment',
            },
        ),
    ]
